//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapleLib.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MapleLib.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action will delete all content currently under
        ///&apos;{0}&apos;.
        /// </summary>
        public static string ActionWillDeleteAllContent {
            get {
                return ResourceManager.GetString("ActionWillDeleteAllContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] CDecrypt_exe_gz {
            get {
                object obj = ResourceManager.GetObject("CDecrypt_exe_gz", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CEMU {
            get {
                object obj = ResourceManager.GetObject("CEMU", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] DLCPatch {
            get {
                object obj = ResourceManager.GetObject("DLCPatch", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 78DA636064106160605803C4220C1036086800312310B780313344F03F01C040630000427521FF.
        /// </summary>
        public static string DLCPatchString {
            get {
                return ResourceManager.GetString("DLCPatchString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edge is a very unstable build, that receives updates often and should be used with caution. Expect errors to be shown, bugs to be present, and program crashes.
        ///
        ///Report errors at http://github.com/Tsume/Maple-Tree..
        /// </summary>
        public static string EdgeBuildNotice {
            get {
                return ResourceManager.GetString("EdgeBuildNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The executable name should be MapleSeed2 with the extension .exe, place correct this. Exiting..
        /// </summary>
        public static string InvalidExecutableName {
            get {
                return ResourceManager.GetString("InvalidExecutableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action will rename all game folders to an organized format.
        ///
        ///See the log window for sample outputs..
        /// </summary>
        public static string OrganizeBtn_Click_ {
            get {
                return ResourceManager.GetString("OrganizeBtn_Click_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Confirm This Action - MapleSeed.
        /// </summary>
        public static string PleaseConfirmAction {
            get {
                return ResourceManager.GetString("PleaseConfirmAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous MapleSeed2 session is still open.
        ///Would you like to kill the previous session and start a new one?.
        /// </summary>
        public static string Session_Still_Open {
            get {
                return ResourceManager.GetString("Session_Still_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [MapleTree]
        ///; generated by MapleTree
        ///.
        /// </summary>
        public static string Settings_DefaultSettings {
            get {
                return ResourceManager.GetString("Settings_DefaultSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}
        ///{1}.
        /// </summary>
        public static string ThreadException {
            get {
                return ResourceManager.GetString("ThreadException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TITLES = http://www.gametdb.com (type: WiiU language: ORIG version: 20171005180418)
        ///AAFD01 = Bayonetta
        ///AAFE01 = Bayonetta
        ///AAFJ01 = ベヨネッタ
        ///AAFP01 = Bayonetta
        ///AALE01 = Animal Crossing: amiibo Festival
        ///AALJ01 = どうぶつの森amiiboフェスティバル
        ///AALP01 = Animal Crossing: amiibo Festival
        ///ABAE01 = Mario Party 10
        ///ABAJ01 = マリオパーティ10
        ///ABAP01 = Mario Party 10
        ///ABBEVZ = Barbie: Dreamhouse Party
        ///ABBPVZ = Barbie: Dreamhouse Party
        ///ABEEG9 = Ben 10: Omniverse
        ///ABEPAF = Ben 10: Omniverse
        ///ABFE52 = Rapala Pro Bass Fishing
        ///ABHE0 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string wiiutdb {
            get {
                return ResourceManager.GetString("wiiutdb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;titleID&quot;:&quot;000500001010f300&quot;,&quot;titleKey&quot;:&quot;fa37b75fd0de03d2a297471477066c7c&quot;,&quot;name&quot;:&quot;Family Party\n30 Great Games Obstacle Arcade&quot;,&quot;region&quot;:&quot;USA&quot;,&quot;ticket&quot;:&quot;1&quot;},{&quot;titleID&quot;:&quot;0005000010144000&quot;,&quot;titleKey&quot;:&quot;e44b226422eb84923c05ccddc62ad487&quot;,&quot;name&quot;:&quot;Adventure Time: Explore the \nDungeon Because I Don&apos;t Know!&quot;,&quot;region&quot;:&quot;USA&quot;,&quot;ticket&quot;:&quot;1&quot;},{&quot;titleID&quot;:&quot;0005000010145e00&quot;,&quot;titleKey&quot;:&quot;4e330266ba3feba347e186ac499ba64e&quot;,&quot;name&quot;:&quot;Angry Birds Star Wars&quot;,&quot;region&quot;:&quot;USA&quot;,&quot;ticket&quot;:&quot;1&quot;},{&quot;titleID&quot;:&quot;0005000010147b00&quot;,&quot;titleKey&quot;:&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string wiiutitlekeys {
            get {
                return ResourceManager.GetString("wiiutitlekeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action will delete all contents under the directory {0}.
        /// </summary>
        public static string WillDeleteContents {
            get {
                return ResourceManager.GetString("WillDeleteContents", resourceCulture);
            }
        }
    }
}
