image: Visual Studio 2017
branches:
  only:
    - master

environment:
  matrix:
    - platform: amd64
      qt: msvc2017_64

init:
  - if not %platform%==mingw set PATH=C:\Qt\5.12\%qt%\bin;%PATH%
    
install:
  - set PATH=%PATH%;C:\Qt\Tools\msvc2017

build_script:
  - call scripts\version.bat
  - qmake MapleSeed.pro
  - msvc2017

artifacts:
  - path: bin\*
    name: mapleseed