image: Visual Studio 2017
branches:
  only:
    - master

environment:
  matrix:
    - platform: amd64
      qt: msvc2017_64
      
install:
  - set QTDIR=C:\Qt\5.12\msvc2017_64
  - set PATH=%QTDIR%\bin;C:\Qt\Tools\mingw530_32\bin;%PATH%;

build_script:
  - call scripts\version.cmd
  - qmake MapleSeed.pro -spec win32-msvc
  - qmake_all
  - C:\Qt\Tools\QtCreator\bin\jom.exe -f Makefile.Release

artifacts:
  - path: bin\*
    name: mapleseed