image: Visual Studio 2017
branches:
  only:
    - master

environment:
  matrix:
    - platform: amd64
      qt: msvc2017_64

init:
  - if not %platform%==mingw call "C:\Qt\5.12\msvc2017_64\bin\qtenv2.bat"
  - if not %platform%==mingw call "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" %platform%
  - if not %platform%==mingw (set makefiles="NMake Makefiles") else (set makefiles="MinGW Makefiles")
  - cd "C:\projects\maple-tree"
      
install:
  - set QTDIR=C:\Qt\5.12\msvc2017_64
  - set PATH=%QTDIR%;%QTDIR%\bin;C:\Qt\Tools\mingw530_32\bin;%PATH%;

build_script:
  - call scripts\version.cmd
  - qmake MapleSeed.pro -spec win32-msvc
  - C:\Qt\Tools\QtCreator\bin\jom.exe -f Makefile.Release

artifacts:
  - path: bin\*
    name: mapleseed